### ISSUE TITLE
Set up Scenarios for demo

### ISSUE THREAD

**Issue by zegermouw** [delftdata/hci-auto-feat#31]

**Comment by AndraIonescu** [comment]
Scenario 1

- initiate autofeat with the base table, the target variable and dataset repository 
- run the automatic augmentation with `explain=True`
- print the best performing tree: print the join paths, the selected features, the model name, the accuracy, the feature importances

Print Screen with one notebook cell containing: 
- autofeat initialisation 
- run the automatic augmentation with `explain=True`
- the output of the cell is the explanation

**Comment by AndraIonescu** [comment]
Scenario 2 

a) Manipulate Relationships 

- find relationships using Jaccard 
- display the heatmap with the best relationships
- display the heatmap between `base` and `crime`
- run the augmentation
- update the weight of DBN to 0.2 (below the threshold) 
- display the new heatmap between `base` and `crime`
- run the augmentation again 

Behaviour: the join trees should not contain the `crime` dataset anymore. 

- [x] Print screen with one notebook cell:
- find relationships
- display big heatmap
- display small heatmap 

- [x] Save each heatmap and send them to me. 
`plt.savefig('heatmap.pdf', dpi=300, bbox_inches="tight")`

- [ ] Print screen with one notebook cell: 
- run the augmentation and print the accuracy and the model
- update the weights 
- run the augmentation and print the accuracy and the model 
- (the output of the cell should be the two results of the augmentation) 

b) Manipulate Join Paths 

- display the join trees 
- inspect a tree (with at least 2 tables) 
- evaluate the tree
- remove a path from the tree 
- inspect the features of this tree
- evaluate the tree again 

Behaviour: the selected features should be different and the accuracy of the tree should change. 

- [x] Print screen with one notebook cell: 
- display the trees 

- [ ] Save each tree and send them to me 
`plt.savefig('join_tree_{id}.pdf', dpi=300, bbox_inches="tight")`

- [x] Print screen with one notebook cell:
- inspect a tree 
- the output of the cell 

- [x] Print screen with one notebook cell:
- evaluate the tree
- remove a path 
- evaluate again 
- the output should have the scores from each evaluation 

c) Manipulate Features 

- inspect a join tree
- display the features
- evaluate the tree
- move a feature from selected to discarded
- move a feature from discarded to selected
- evaluate the tree 

Behaviour: the accuracy should change. 

- [x] Print screen with one notebook cell:
- display the features (discarded also) 

- [x] Print screen with one notebook cell:
- evaluate the tree
- move a feature from selected to discarded
- move a feature from discarded to selected
- evaluate the tree 
- the output of the two evaluate runs
